export const rarities = {
    RARITY_R: 'r',
    RARITY_SR: 'sr',
    RARITY_SSR: 'ssr',
    RARITY_SSR_EVENT: 'ssr_event',
}

export const displayRarities = {
    RARITY_R: 'R',
    RARITY_SR: 'SR',
    RARITY_SSR: 'SSR',
}

export const levels = {
    MIN_LEVEL: 1,
    R_MAX_LEVEL: 40,
    SR_MAX_LEVEL: 50,
    SSR_MAX_LEVEL: 60,
}

export const types = {
    VOCAL: 'ボーカル',
    DANCE: 'ダンス',
    VISUAL: 'ビジュアル',
    ASSIST: 'アシスト',
}

export const plans = {
    FREE: 'プラン制限なし',
    SENSE: 'センス限定',
    LOGIC: 'ロジック限定',
    ANOMALY: 'アノマリー限定',
}

export const events = {
    NONE: 'none',
    // 固有Pアイテム獲得
    GET_UNIQUE_P_ITEM: 'get_unique_p_item',
    // 固有スキルカード獲得
    GET_UNIQUE_CARD: 'get_unique_card',
    // パラメータ上昇
    PARAMETER_UP: 'parameter_up',
    // HP回復
    HP_RECOVER: 'hp_recover',
    // Pポイント獲得
    GET_P_POINT: 'get_p_point',
    // 基本スキルカード変換
    BASIC_CARD_CHANGE: 'basic_card_change',
    // スキルカードランダム強化
    CARD_RANDOM_STRENGTHEN: 'card_random_strengthen',
    // トラブルカードランダム削除
    TROUBLE_CARD_DELETE: 'trouble_card_delete',
    // スキルカード選択強化
    CARD_SELECT_STRENGTHEN: 'card_select_strengthen',
    // スキルカード選択削除
    CARD_SELECT_DELETE: 'card_select_delete',
}

export const abilities = {
    NONE: 'none',
    // 初期パラメータ上昇
    INIT_PARAMETER_UP: 'init_parameter_up',
    // パラメータボーナス
    PARAMETER_BONUS: 'parameter_bonus',
    // 最大体力上昇
    MAX_HP_UP: 'max_hp_up',
    // 初期Pポイント上昇
    INIT_P_POINT: 'init_p_point',
    // スキルカードサポート発生率増加
    CARD_SUPPORT_RATE: 'card_support_rate',
    // サポートカードイベント2強化
    EVENT_STRENGTHEN: 'event_strengthen',
    // SPレッスン発生率増加
    SP_LESSON_RATE: 'sp_lesson_rate',
    // レッスン終了時パラメータ上昇
    LESSON_PARAMETER_UP: 'lesson_parameter_up',
    // 通常レッスン終了時パラメータ上昇
    NORMAL_LESSON_PARAMETER_UP: 'normal_lesson_parameter_up',
    // SPレッスン終了時パラメータ上昇
    SP_LESSON_PARAMETER_UP: 'sp_lesson_parameter_up',
    // アクティブカード獲得時パラメータ上昇
    ACTIVE_CARD_PARAMETER_UP: 'active_card_parameter_up',
    // メンタルカード獲得時パラメータ上昇
    MENTAL_CARD_PARAMETER_UP: 'mental_card_parameter_up',
    // 好調効果カード獲得時パラメータ上昇
    KOTYO_CARD_PARAMETER_UP: 'kotyo_card_parameter_up',
    // スキルカード強化時パラメータ上昇
    CARD_STRENGTHEN_PARAMETER_UP: 'card_strengthen_parameter_up',
    // アクティブカード強化時パラメータ上昇
    ACTIVE_CARD_STRENGTHEN_PARAMETER_UP: 'active_card_strengthen_parameter_up',
    // メンタルカード強化時パラメータ上昇
    MENTAL_CARD_STRENGTHEN_PARAMETER_UP: 'mental_card_strengthen_parameter_up',
    // スキルカード削除時パラメータ上昇
    CARD_DELETE_PARAMETER_UP: 'card_delete_parameter_up',
    // 授業・営業終了時パラメータ上昇
    CLASS_PARAMETER_UP: 'class_parameter_up',
    // 活動支給・差し入れ選択時パラメータ上昇
    GIFT_PARAMETER_UP: 'gift_parameter_up',
    // お出かけ終了時パラメータ上昇
    OUTING_PARAMETER_UP: 'outing_parameter_up',
    // 相談選択時パラメータ上昇
    CONSULTATION_PARAMETER_UP: 'consultation_parameter_up',
    // 相談でPドリンク交換後パラメータ上昇
    CONSULTATION_DRINK_PARAMETER_UP: 'consultation_drink_parameter_up',
    // 休む選択時パラメータ上昇
    REST_PARAMETER_UP: 'rest_parameter_up',
    // 試験・オーディション終了時パラメータ上昇
    EXAM_PARAMETER_UP: 'exam_parameter_up',
    // レッスン終了時Pポイント獲得量増加
    LESSON_P_POINT_UP: 'lesson_p_point_up',
    // SPレッスン終了時Pポイント獲得量増加
    SP_LESSON_P_POINT_UP: 'sp_lesson_p_point_up',
    // SPレッスン終了時体力回復
    SP_LESSON_HP_RECOVER: 'sp_lesson_hp_recover',
    // 活動支給・差し入れ選択時体力回復
    GIFT_HP_RECOVER: 'gift_hp_recover',
    // 試験・オーディション終了時体力回復
    EXAM_HP_RECOVER: 'exam_hp_recover',
    // 相談のPドリンク割引
    CONSULTATION_DRINK_SALE: 'consultation_drink_sale',
}

export const abilityParameterThresholds = {
    r: {
        ability_2: [1, 15, 41],
        ability_4: [5, 36, 41],
        ability_5: [10, 26, 41],
        ability_6: [21, 31, 40],
    },
    sr: {
        ability_2: [1, 31, 51],
        ability_4: [5, 46, 51],
        ability_5: [10, 41, 51],
        ability_6: [25, 36, 50],
    },
    ssr: {
        ability_2: [1, 15, 46],
        ability_4: [5, 30, 51],
        ability_5: [10, 35, 56],
        ability_6: [25, 41, 60],
    },
    ssr_event: {
        ability_2: [1, 46, 61],
        ability_4: [5, 56, 61],
        ability_5: [10, 51, 61],
        ability_6: [25, 41, 60],
    },
}

export const cards = {
    // レアリティ:SSR
    1: {
        id: 1,
        sort_id: 17,
        name: 'あなたにも作ってあげる！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.BASIC_CARD_CHANGE
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.REST_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2: {
        id: 2,
        sort_id: 16,
        name: 'こいつらめんどくさー',
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_P_POINT_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.MENTAL_CARD_STRENGTHEN_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    3: {
        id: 3,
        sort_id: 15,
        name: 'お姉ちゃんに任せなさい！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_P_POINT_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    4: {
        id: 4,
        sort_id: 14,
        name: 'ぐぬぬぬぬ…………！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.BASIC_CARD_CHANGE
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.GIFT_PARAMETER_UP,
        ability_5: abilities.MENTAL_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    5: {
        id: 5,
        sort_id: 13,
        name: '次の桜の季節には。',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    6: {
        id: 6,
        sort_id: 12,
        name: 'お疲れ様、千奈ちゃん。',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.ACTIVE_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    7: {
        id: 7,
        sort_id: 11,
        name: 'まるで王子様みたいな',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.MENTAL_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    8: {
        id: 8,
        sort_id: 10,
        name: 'おいしい顔、いただき～！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    9: {
        id: 9,
        sort_id: 9,
        name: 'わたしたち、やればできる',
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_P_POINT_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.MENTAL_CARD_STRENGTHEN_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    10: {
        id: 10,
        sort_id: 8,
        name: '可愛いと可愛いで可愛い！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.ACTIVE_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    11: {
        id: 11,
        sort_id: 7,
        name: '私の目に狂いはない',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.BASIC_CARD_CHANGE
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.CLASS_PARAMETER_UP,
        ability_5: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    12: {
        id: 12,
        sort_id: 6,
        name: 'また、あんなに無理をして',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.OUTING_PARAMETER_UP,
        ability_5: abilities.MENTAL_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    13: {
        id: 13,
        sort_id: 5,
        name: 'あら、奇遇ね',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    14: {
        id: 14,
        sort_id: 4,
        name: 'まじか。',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_P_POINT_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    15: {
        id: 15,
        sort_id: 3,
        name: '仕事のつもりで臨みなさい',
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.TROUBLE_CARD_DELETE
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.MENTAL_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    16: {
        id: 16,
        sort_id: 2,
        name: 'ほら、一緒に持と♪',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.BASIC_CARD_CHANGE
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.ACTIVE_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    17: {
        id: 17,
        sort_id: 1,
        name: 'きみは、自慢の生徒です',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.ASSIST,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.HP_RECOVER,
            event_3: events.CARD_SELECT_STRENGTHEN
        },
        ability_1: abilities.MAX_HP_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_HP_RECOVER,
        ability_5: abilities.EXAM_HP_RECOVER,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    18: {
        id: 18,
        sort_id: 18,
        name: '第2回教室パーティー！',
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.EXAM_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    19: {
        id: 19,
        sort_id: 19,
        name: '何やってるんだろう、',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.BASIC_CARD_CHANGE
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    20: {
        id: 20,
        sort_id: 20,
        name: 'まだ上がりませんように！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.MENTAL_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    21: {
        id: 21,
        sort_id: 21,
        name: '晴れたね',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.REST_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    22: {
        id: 22,
        sort_id: 22,
        name: '「ア」じゃなくて「エ」！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.MENTAL_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    23: {
        id: 23,
        sort_id: 23,
        name: 'もうっ！　冷たいよ！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.EXAM_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    24: {
        id: 24,
        sort_id: 24,
        name: '一時休戦です',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.BASIC_CARD_CHANGE
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    25: {
        id: 25,
        sort_id: 25,
        name: '夏を楽しみましょう！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_DRINK_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    26: {
        id: 26,
        sort_id: 26,
        name: '花火、やりませんか……？',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.ACTIVE_CARD_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    27: {
        id: 27,
        sort_id: 27,
        name: '夏を満喫するわよ！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.MENTAL_CARD_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    28: {
        id: 28,
        sort_id: 28,
        name: 'あっちも行きたいですわ！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.ACTIVE_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    29: {
        id: 29,
        sort_id: 29,
        name: 'ゆっくりと過ごしましょう',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_DRINK_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    30: {
        id: 30,
        sort_id: 30,
        name: '新たな挑戦の成功ですわ！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.ACTIVE_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    31: {
        id: 31,
        sort_id: 31,
        name: '1人たりとも欠ける事なく',
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_HP_RECOVER,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    32: {
        id: 32,
        sort_id: 32,
        name: '二人ならあっという間だね',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.CLASS_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_5: abilities.SP_LESSON_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    33: {
        id: 33,
        sort_id: 33,
        name: '似合うんじゃない？',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    34: {
        id: 34,
        sort_id: 34,
        name: 'すっかり秋色ですわね！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.KOTYO_CARD_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    35: {
        id: 35,
        sort_id: 35,
        name: '会長、準備は万端です',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.MENTAL_CARD_STRENGTHEN_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    36: {
        id: 36,
        sort_id: 36,
        name: '食欲の秋なんです',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.ASSIST,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.HP_RECOVER,
            event_3: events.CARD_SELECT_DELETE
        },
        ability_1: abilities.MAX_HP_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_P_POINT_UP,
        ability_5: abilities.INIT_P_POINT,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    37: {
        id: 37,
        sort_id: 37,
        name: 'そろそろ焼けたかな？',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    38: {
        id: 38,
        sort_id: 38,
        name: 'ぜったい追いついてやる！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.CLASS_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_5: abilities.SP_LESSON_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    39: {
        id: 39,
        sort_id: 39,
        name: 'プロデュースって大変ね',
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.ANOMALY,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.GIFT_HP_RECOVER,
        ability_5: abilities.EXAM_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    40: {
        id: 40,
        sort_id: 40,
        name: 'さみだれ',
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.ANOMALY,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_P_POINT_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.MENTAL_CARD_STRENGTHEN_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    41: {
        id: 41,
        sort_id: 41,
        name: 'キラキラして綺麗～っ！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.CONSULTATION_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.EXAM_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    42: {
        id: 42,
        sort_id: 42,
        name: 'あったかいね',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.MENTAL_CARD_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    43: {
        id: 43,
        sort_id: 43,
        name: '待ちなさーい！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.ANOMALY,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.ACTIVE_CARD_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    44: {
        id: 44,
        sort_id: 44,
        name: 'もう一度、最初から！',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    45: {
        id: 45,
        sort_id: 45,
        name: 'これが私たちの、3年間',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    46: {
        id: 46,
        sort_id: 46,
        name: 'はいっ、みんなも一緒に♪',
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        level: levels.SSR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.ANOMALY,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
            event_3: events.CARD_RANDOM_STRENGTHEN
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_HP_RECOVER,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    // レアリティ:SR
    1001: {
        id: 1001,
        sort_id: 15,
        name: '体当たりのラブコール',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.EXAM_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1002: {
        id: 1002,
        sort_id: 14,
        name: '今はあえて、背を向けて',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.EXAM_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1003: {
        id: 1003,
        sort_id: 13,
        name: 'のらりくらりしっかり',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1004: {
        id: 1004,
        sort_id: 12,
        name: '愛無き暗記は難しい',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.NORMAL_LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1005: {
        id: 1005,
        sort_id: 11,
        name: 'てとりあしとり',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1006: {
        id: 1006,
        sort_id: 10,
        name: 'ほっぺた、ぷに',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.NORMAL_LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1007: {
        id: 1007,
        sort_id: 9,
        name: '魅惑の大腿四頭筋',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1008: {
        id: 1008,
        sort_id: 8,
        name: 'ふわふわでワクワク',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.EXAM_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1009: {
        id: 1009,
        sort_id: 7,
        name: '嬉し恥ずかし夢心地',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.NORMAL_LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1010: {
        id: 1010,
        sort_id: 6,
        name: '実食！例のSSD',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1011: {
        id: 1011,
        sort_id: 5,
        name: 'マイペース、マイライフ',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1012: {
        id: 1012,
        sort_id: 4,
        name: '思惑とガクガク',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1013: {
        id: 1013,
        sort_id: 3,
        name: 'ほっとけないクラスメイト',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.LESSON_P_POINT_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1014: {
        id: 1014,
        sort_id: 2,
        name: 'いつか、きっと花開く',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.LESSON_P_POINT_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_5: abilities.REST_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1015: {
        id: 1015,
        sort_id: 1,
        name: 'はじめてのお友達',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.ASSIST,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.GET_P_POINT,
        },
        ability_1: abilities.INIT_P_POINT,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.CONSULTATION_DRINK_SALE,
        ability_5: abilities.LESSON_P_POINT_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1016: {
        id: 1016,
        sort_id: 16,
        name: 'イヤホンはんぶんこ',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.REST_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1017: {
        id: 1017,
        sort_id: 17,
        name: 'パシャっとキメポ',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.REST_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1018: {
        id: 1018,
        sort_id: 18,
        name: 'どりゃぎゃ',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1019: {
        id: 1019,
        sort_id: 19,
        name: 'かちこちストレッチ',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.LESSON_P_POINT_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1020: {
        id: 1020,
        sort_id: 20,
        name: '海、楽しまなきゃ！',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.LESSON_P_POINT_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_HP_RECOVER,
        ability_5: abilities.REST_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1021: {
        id: 1021,
        sort_id: 21,
        name: '第五種接近遭遇',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1022: {
        id: 1022,
        sort_id: 22,
        name: 'やさしさ、あったかい',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1023: {
        id: 1023,
        sort_id: 23,
        name: 'ふわふわなお面？',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1024: {
        id: 1024,
        sort_id: 24,
        name: 'キュっと締めて',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_HP_RECOVER,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_DRINK_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1025: {
        id: 1025,
        sort_id: 25,
        name: 'りっぱなすすき！',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.OUTING_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1026: {
        id: 1026,
        sort_id: 26,
        name: 'ブレイクタイムは珈琲で',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_DRINK_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1027: {
        id: 1027,
        sort_id: 27,
        name: '千奈の恩返し',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.CARD_DELETE_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1028: {
        id: 1028,
        sort_id: 28,
        name: '興味深い飲み物',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1029: {
        id: 1029,
        sort_id: 29,
        name: 'SSDのひみつ',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1030: {
        id: 1030,
        sort_id: 30,
        name: 'トンボをつかまえて',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.EXAM_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1031: {
        id: 1031,
        sort_id: 31,
        name: 'バズっちゃお！',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.CONSULTATION_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.OUTING_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1032: {
        id: 1032,
        sort_id: 32,
        name: 'サンマ、パタパタ',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1033: {
        id: 1033,
        sort_id: 33,
        name: 'ディカプルエックスエル！',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.SENSE,
        events: {
            event_1: events.GET_UNIQUE_CARD,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.CONSULTATION_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1034: {
        id: 1034,
        sort_id: 34,
        name: 'きゅる～んωポーズッ☆',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.LOGIC,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.SP_LESSON_RATE,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.EXAM_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    1035: {
        id: 1035,
        sort_id: 35,
        name: 'カロリー/2でハッピー×2',
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        level: levels.SR_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_1: events.GET_UNIQUE_P_ITEM,
            event_2: events.PARAMETER_UP,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.CARD_STRENGTHEN_PARAMETER_UP,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.SP_LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    // レアリティ:R
    2001: {
        id: 2001,
        sort_id: 12,
        name: '念入りにストレッチ',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.REST_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2002: {
        id: 2002,
        sort_id: 11,
        name: '全力、その後',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.REST_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2003: {
        id: 2003,
        sort_id: 10,
        name: '枝毛をくるり',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.REST_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2004: {
        id: 2004,
        sort_id: 9,
        name: '王子様のひと呼吸',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.NORMAL_LESSON_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2005: {
        id: 2005,
        sort_id: 8,
        name: 'ひたむき居残りレッスン',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.NORMAL_LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2006: {
        id: 2006,
        sort_id: 7,
        name: '憧れを目指して',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.INIT_PARAMETER_UP,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.NORMAL_LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2007: {
        id: 2007,
        sort_id: 6,
        name: 'スイッチON！',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2008: {
        id: 2008,
        sort_id: 5,
        name: 'いめーじとれーにんぐ',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2009: {
        id: 2009,
        sort_id: 4,
        name: '完全無欠のプランニング',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2010: {
        id: 2010,
        sort_id: 3,
        name: 'わたしのペースで',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.VOCAL,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.NORMAL_LESSON_PARAMETER_UP,
        ability_5: abilities.GIFT_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2011: {
        id: 2011,
        sort_id: 2,
        name: 'お姉ちゃん直伝メニュー',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.DANCE,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.NORMAL_LESSON_PARAMETER_UP,
        ability_5: abilities.CLASS_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
    2012: {
        id: 2012,
        sort_id: 1,
        name: '頼れる先輩お姉さん',
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        level: levels.R_MAX_LEVEL,
        type: types.VISUAL,
        plan: plans.FREE,
        events: {
            event_2: events.PARAMETER_UP,
            event_3: events.GET_P_POINT,
        },
        ability_1: abilities.PARAMETER_BONUS,
        ability_2: abilities.INIT_P_POINT,
        ability_3: abilities.CARD_SUPPORT_RATE,
        ability_4: abilities.NORMAL_LESSON_PARAMETER_UP,
        ability_5: abilities.OUTING_PARAMETER_UP,
        ability_6: abilities.EVENT_STRENGTHEN,
    },
}