export const DEAR_MAX_LEVEL = 20;
export const TRAINING_MAX_LEVEL = 6;
export const TALENT_BLOSSOMING_MAX_LEVEL = 4;

export const rarities = {
    RARITY_R: 'r',
    RARITY_SR: 'sr',
    RARITY_SSR: 'ssr',
    RARITY_SSR_EVENT: 'ssr_event',
}

export const displayRarities = {
    RARITY_R: 'R',
    RARITY_SR: 'SR',
    RARITY_SSR: 'SSR',
}

export const plans = {
    SENSE: 'センス',
    LOGIC: 'ロジック',
    ANOMALY: 'アノマリー',
}

export const effects = {
    KOTYO: '好調',
    SYUTYU: '集中',
    YARUKI: 'やる気',
    KOINSYO: '好印象',
    TUYOKI: '強気',
    ZENRYOKU: '全力',
}

export const idols = {
    saki: {
        id: 1,
        name: '花海咲季',
        dear: DEAR_MAX_LEVEL,
    },
    temari: {
        id: 2,
        name: '月村手毬',
        dear: DEAR_MAX_LEVEL,
    },
    kotone: {
        id: 3,
        name: '藤田ことね',
        dear: DEAR_MAX_LEVEL,
    },
    mao: {
        id: 4,
        name: '有村麻央',
        dear: DEAR_MAX_LEVEL,
    },
    lilja: {
        id: 5,
        name: '葛城リーリヤ',
        dear: DEAR_MAX_LEVEL,
    },
    china: {
        id: 6,
        name: '倉本千奈',
        dear: DEAR_MAX_LEVEL,
    },
    sumika: {
        id: 7,
        name: '紫雲清夏',
        dear: DEAR_MAX_LEVEL,
    },
    hiro: {
        id: 8,
        name: '篠澤広',
        dear: DEAR_MAX_LEVEL,
    },
    sena: {
        id: 11,
        name: '十王星南',
        dear: DEAR_MAX_LEVEL,
    },
    misuzu: {
        id: 12,
        name: '秦谷美鈴',
        dear: 0,
    },
    ume: {
        id: 10,
        name: '花海佑芽',
        dear: DEAR_MAX_LEVEL,
    },
    rinami: {
        id: 9,
        name: '姫崎莉波',
        dear: DEAR_MAX_LEVEL,
    },
}

export const produces = {
    // レアリティ:SSR
    1: {
        id: 1,
        idol_id: idols.saki.id,
        name: 'Fighting My Way',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    2: {
        id: 2,
        idol_id: idols.temari.id,
        name: 'Luna say maybe',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    3: {
        id: 3,
        idol_id: idols.kotone.id,
        name: '世界一可愛い私',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    4: {
        id: 4,
        idol_id: idols.mao.id,
        name: 'Fluorite',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    5: {
        id: 5,
        idol_id: idols.lilja.id,
        name: '白線',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    6: {
        id: 6,
        idol_id: idols.china.id,
        name: 'Wonder Scale',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    7: {
        id: 7,
        idol_id: idols.sumika.id,
        name: 'Tame-Lie-One-Step',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    8: {
        id: 8,
        idol_id: idols.hiro.id,
        name: '光景',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    9: {
        id: 9,
        idol_id: idols.rinami.id,
        name: 'clumsy trick',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    10: {
        id: 10,
        idol_id: idols.temari.id,
        name: 'アイヴイ',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    11: {
        id: 11,
        idol_id: idols.ume.id,
        name: 'The Rolling Riceball',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    12: {
        id: 12,
        idol_id: idols.kotone.id,
        name: 'Yellow Big Bang！',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    13: {
        id: 13,
        idol_id: idols.saki.id,
        name: 'Boom Boom Pow',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    14: {
        id: 14,
        idol_id: idols.mao.id,
        name: 'キミとセミブルー',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    15: {
        id: 15,
        idol_id: idols.sumika.id,
        name: 'キミとセミブルー',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    16: {
        id: 16,
        idol_id: idols.rinami.id,
        name: 'キミとセミブルー',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    17: {
        id: 17,
        idol_id: idols.hiro.id,
        name: 'コントラスト',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    18: {
        id: 18,
        idol_id: idols.saki.id,
        name: '冠菊',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    19: {
        id: 19,
        idol_id: idols.lilja.id,
        name: '冠菊',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    20: {
        id: 20,
        idol_id: idols.kotone.id,
        name: '冠菊',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    21: {
        id: 21,
        idol_id: idols.china.id,
        name: '日々、発見的ステップ！',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    22: {
        id: 22,
        idol_id: idols.rinami.id,
        name: 'ようこそ初星温泉',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    23: {
        id: 23,
        idol_id: idols.china.id,
        name: 'ようこそ初星温泉',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    24: {
        id: 24,
        idol_id: idols.mao.id,
        name: 'Feel Jewel Dream',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    25: {
        id: 25,
        idol_id: idols.china.id,
        name: '仮装狂騒曲',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    26: {
        id: 26,
        idol_id: idols.temari.id,
        name: '仮装狂騒曲',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    27: {
        id: 27,
        idol_id: idols.hiro.id,
        name: '仮装狂騒曲',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    28: {
        id: 28,
        idol_id: idols.rinami.id,
        name: 'L.U.V',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    29: {
        id: 29,
        idol_id: idols.saki.id,
        name: '古今東西ちょちょいのちょい',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    30: {
        id: 30,
        idol_id: idols.sena.id,
        name: '小さな野望',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.ANOMALY,
        effect: effects.TUYOKI,
    },
    31: {
        id: 31,
        idol_id: idols.kotone.id,
        name: 'White Night! White Wish!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR_EVENT,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    32: {
        id: 32,
        idol_id: idols.ume.id,
        name: 'White Night! White Wish!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    33: {
        id: 33,
        idol_id: idols.lilja.id,
        name: 'White Night! White Wish!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    34: {
        id: 34,
        idol_id: idols.sumika.id,
        name: 'カクシタワタシ',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.ANOMALY,
        effect: effects.ZENRYOKU,
    },
    35: {
        id: 35,
        idol_id: idols.saki.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    36: {
        id: 36,
        idol_id: idols.temari.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    37: {
        id: 37,
        idol_id: idols.kotone.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    38: {
        id: 38,
        idol_id: idols.mao.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.ANOMALY,
        effect: effects.TUYOKI,
    },
    39: {
        id: 39,
        idol_id: idols.sena.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    40: {
        id: 40,
        idol_id: idols.rinami.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.ANOMALY,
        effect: effects.ZENRYOKU,
    },
    41: {
        id: 41,
        idol_id: idols.china.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    42: {
        id: 42,
        idol_id: idols.hiro.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    43: {
        id: 43,
        idol_id: idols.ume.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.ANOMALY,
        effect: effects.ZENRYOKU,
    },
    44: {
        id: 44,
        idol_id: idols.lilja.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    45: {
        id: 45,
        idol_id: idols.sumika.id,
        name: 'Campus mode!!',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SSR,
        rarity_display: displayRarities.RARITY_SSR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    // レアリティ:SR
    1001: {
        id: 1001,
        idol_id: idols.saki.id,
        name: 'わたしが一番！',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    1002: {
        id: 1002,
        idol_id: idols.temari.id,
        name: '一匹狼',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    1003: {
        id: 1003,
        idol_id: idols.kotone.id,
        name: 'カワイイ♡はじめました',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    1004: {
        id: 1004,
        idol_id: idols.mao.id,
        name: 'はじまりはカッコよく',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    1005: {
        id: 1005,
        idol_id: idols.lilja.id,
        name: '一つ踏み出した先に',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    1006: {
        id: 1006,
        idol_id: idols.china.id,
        name: '胸を張って一歩ずつ',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    1007: {
        id: 1007,
        idol_id: idols.sumika.id,
        name: '夢へのリスタート',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    1008: {
        id: 1008,
        idol_id: idols.hiro.id,
        name: '一番向いていないこと',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    1009: {
        id: 1009,
        idol_id: idols.rinami.id,
        name: '『私らしさ』のはじまり',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    1010: {
        id: 1010,
        idol_id: idols.ume.id,
        name: 'アイドル、はじめっ！',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    1011: {
        id: 1011,
        idol_id: idols.sena.id,
        name: '一番星',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_SR,
        rarity_display: displayRarities.RARITY_SR,
        plan: plans.ANOMALY,
        effect: effects.ZENRYOKU,
    },
    // レアリティ:R
    2001: {
        id: 2001,
        idol_id: idols.saki.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    2002: {
        id: 2002,
        idol_id: idols.temari.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    2003: {
        id: 2003,
        idol_id: idols.kotone.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    2004: {
        id: 2004,
        idol_id: idols.mao.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    2005: {
        id: 2005,
        idol_id: idols.lilja.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    2006: {
        id: 2006,
        idol_id: idols.china.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    2007: {
        id: 2007,
        idol_id: idols.sumika.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    2008: {
        id: 2008,
        idol_id: idols.hiro.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    2009: {
        id: 2009,
        idol_id: idols.rinami.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.SENSE,
        effect: effects.SYUTYU,
    },
    2010: {
        id: 2010,
        idol_id: idols.ume.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    2011: {
        id: 2011,
        idol_id: idols.saki.id,
        name: '初声',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    2012: {
        id: 2012,
        idol_id: idols.temari.id,
        name: '初声',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    2013: {
        id: 2013,
        idol_id: idols.kotone.id,
        name: '初声',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    2014: {
        id: 2014,
        idol_id: idols.lilja.id,
        name: '初心',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    2015: {
        id: 2015,
        idol_id: idols.china.id,
        name: '初心',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.SENSE,
        effect: effects.KOTYO,
    },
    2016: {
        id: 2016,
        idol_id: idols.rinami.id,
        name: '初心',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    2017: {
        id: 2017,
        idol_id: idols.mao.id,
        name: '初恋',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.KOINSYO,
    },
    2018: {
        id: 2018,
        idol_id: idols.sumika.id,
        name: '初恋',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    2019: {
        id: 2019,
        idol_id: idols.hiro.id,
        name: '初恋',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.LOGIC,
        effect: effects.YARUKI,
    },
    2020: {
        id: 2020,
        idol_id: idols.sena.id,
        name: '学園生活',
        training_level: TRAINING_MAX_LEVEL,
        talent_blossoming_level: TALENT_BLOSSOMING_MAX_LEVEL,
        rarity: rarities.RARITY_R,
        rarity_display: displayRarities.RARITY_R,
        plan: plans.ANOMALY,
        effect: effects.TUYOKI,
    },
}
